name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ebooks-aura/package-lock.json

      - name: Install dependencies
        run: |
          cd ebooks-aura
          npm ci
          npm install cross-env rimraf --save-dev

      - name: Clean build directories
        run: |
          cd ebooks-aura
          npm run clean

      - name: Build static site
        run: |
          cd ebooks-aura
          STATIC_EXPORT=true NEXT_PUBLIC_API_URL=https://ebookaura.onrender.com/api next build
        env:
          STATIC_EXPORT: "true"
          NEXT_PUBLIC_API_URL: "https://ebookaura.onrender.com/api"

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ebooks-aura/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 