[build]
  base = "ebooks-aura/"
  publish = "out"
  command = "npm run build:static:prod"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://ebookaura.onrender.com/api"

# Handle route rewrites for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configure caching
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Cache static assets longer
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 